### PR TITLE
feat: added support of trusted_key_groups

### PR DESCRIPTION
**Pull request by UladzislauValchkou**
## Description
Added support of trusted_key_groups parameter

## Motivation and Context
Pull request solves https://github.com/terraform-aws-modules/terraform-aws-cloudfront/issues/30

## Breaking Changes
No breaking changes in scope of pull request.

## How Has This Been Tested?
- [ x] I have tested and validated these changes using one or more of the provided `examples/*` projects
Also tested it with my project's Cloudfront distributions.

### CODE REVIEW

**Comment by antonbabenko** [comment]
Please update the AWS provider version in [versions.tf](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/versions.tf#L5) when this feature was introduced - 3.37.0

**Comment by UladzislauValchkou** [comment]
@antonbabenko , AWS provider version updated in versions.tf

**Comment by antonbabenko** [comment]
Thank you!

[v2.1.0](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/releases/v2.1.0) has been just released.

**Comment by AndriMar** [comment]
@UladzislauValchkou Is it possible you could add this also to the `ordered_cache_behavior`?
I can also fork this repo and do another PR

**Pull request merged**
