### PR TITLE
fix: Update s3_origin_config and custom_origin_config should not create dynamic block when no variable are defined

### PR DESCRIPTION
**Pull request by huzaifa-binafzal**
## Description

Quick fix in the module where it always create a empty block {} for `s3_origin_config `and `custom_origin_config` when we don't pass any value to these variables. There should be no dynamic block created for `s3_origin_config `and `custom_origin_config` when we don't define any value for the variable. 

## Motivation and Context
Why is this change required? What problem does it solve?

We have fix it by changing the `for_each` condition for `s3_origin_config `and `custom_origin_config` dynamic block where it will not create any dynamic block for these resources if we don't pass any value for these variable. 

This will fix the current issue where a dynamic block is created for `s3_origin_config `and `custom_origin_config` when we don't define any value for the variable. 

## Breaking Changes
Does this break backwards compatibility with the current major version?
No

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by haytham-salhi** [comment]
Hi @antonbabenko @bryantbiggs, any chance you can help get this merged?

**Comment by antonbabenko** [comment]
Could you provide the reproduction code showing the problem? Then, it will be possible to see what you're trying to fix.

**Comment by haytham-salhi** [comment]
@huzaifa-binafzal can we plz provide @antonbabenko what he requested?

**Comment by huzaifa-binafzal** [comment]
@antonbabenko this is our code. We have the modules file inside `distribution` folder. In our `resources.tf` We are looping over our map of object variable `cloudfront_distributions` in our `variables.tf `. We are passing the values in `main.tf`.

`Problem statement:`

We have multiple cloudfront distributions. 

- Some distributions have s3_origin_config some of them dont have this. But since we are passing default value because of for_each condition it creates the empty s3_origin_config {} for the distributions were we dont have it. The issue is that since the default for_each condition doesn't null the dynamic resources it expects `{} `.

- Some distributions have custom_origin_config but some of them dont have it. But since the module expects the default value to be {} we have to pass the default value as { http_port = 80, https_port = 443, origin_protocol_policy   = "https-only", origin_read_timeout = 30, origin_ssl_protocols = [     "TLSv1.2",   ]} since we have required values in custom_origin_config we cant pass it as empty {}. And if we pass this value the custom_origin_config would also get created for the resources that dont have it. 

If we pass null as default we get error on the module. So we have purposed this change to fix this issue.

See the sample plan here:

````
terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.distributions.module.cloudfront_distributions["test-cf-custom-origin-config"].aws_cloudfront_distribution.this[0] will be created
  + resource "aws_cloudfront_distribution" "this" {
      + arn                             = (known after apply)
      + caller_reference                = (known after apply)
      + continuous_deployment_policy_id = (known after apply)
      + domain_name                     = (known after apply)
      + enabled                         = true
      + etag                            = (known after apply)
      + hosted_zone_id                  = (known after apply)
      + http_version                    = "http2"
      + id                              = (known after apply)
      + in_progress_validation_batches  = (known after apply)
      + is_ipv6_enabled                 = false
      + last_modified_time              = (known after apply)
      + price_class                     = "PriceClass_All"
      + retain_on_delete                = false
      + staging                         = false
      + status                          = (known after apply)
      + tags_all                        = {
          + "Environment"       = "dev"
          + "terraform-project" = "TerraformCloudFront"
        }
      + trusted_key_groups              = (known after apply)
      + trusted_signers                 = (known after apply)
      + wait_for_deployment             = true

      + default_cache_behavior {
          + allowed_methods          = [
              + "DELETE",
              + "GET",
              + "HEAD",
              + "OPTIONS",
              + "PATCH",
              + "POST",
              + "PUT",
            ]
          + cache_policy_id          = "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
          + cached_methods           = [
              + "GET",
              + "HEAD",
            ]
          + compress                 = false
          + default_ttl              = 0
          + max_ttl                  = 0
          + min_ttl                  = 0
          + origin_request_policy_id = "216adef6-5c7f-47e4-b989-5492eafa07d3"
          + target_origin_id         = "Custom-d-i6nfbb6r11.execute-api.us-east-1.amazonaws.com"
          + trusted_key_groups       = (known after apply)
          + trusted_signers          = (known after apply)
          + viewer_protocol_policy   = "redirect-to-https"
        }

      + origin {
          + connection_attempts = 3
          + connection_timeout  = 10
          + domain_name         = "d-i6nfbb6r11.execute-api.us-east-1.amazonaws.com"
          + origin_id           = "Custom-d-i6nfbb6r11.execute-api.us-east-1.amazonaws.com"

          + custom_origin_config {
              + http_port                = 80
              + https_port               = 443
              + origin_keepalive_timeout = 5
              + origin_protocol_policy   = "https-only"
              + origin_read_timeout      = 30
              + origin_ssl_protocols     = [
                  + "TLSv1.2",
                ]
            }

          + s3_origin_config {}
        }

      + restrictions {
          + geo_restriction {
              + locations        = (known after apply)
              + restriction_type = "none"
            }
        }

      + viewer_certificate {
          + cloudfront_default_certificate = true
          + minimum_protocol_version       = "TLSv1"
        }
    }

  # module.distributions.module.cloudfront_distributions["test-s3-origin-config"].aws_cloudfront_distribution.this[0] will be created
  + resource "aws_cloudfront_distribution" "this" {
      + arn                             = (known after apply)
      + caller_reference                = (known after apply)
      + continuous_deployment_policy_id = (known after apply)
      + domain_name                     = (known after apply)
      + enabled                         = true
      + etag                            = (known after apply)
      + hosted_zone_id                  = (known after apply)
      + http_version                    = "http2"
      + id                              = (known after apply)
      + in_progress_validation_batches  = (known after apply)
      + is_ipv6_enabled                 = false
      + last_modified_time              = (known after apply)
      + price_class                     = "PriceClass_All"
      + retain_on_delete                = false
      + staging                         = false
      + status                          = (known after apply)
      + tags_all                        = {
          + "Environment"       = "dev"
          + "terraform-project" = "TerraformCloudFront"
        }
      + trusted_key_groups              = (known after apply)
      + trusted_signers                 = (known after apply)
      + wait_for_deployment             = true

      + default_cache_behavior {
          + allowed_methods        = [
              + "GET",
              + "HEAD",
            ]
          + cached_methods         = [
              + "GET",
              + "HEAD",
            ]
          + compress               = false
          + default_ttl            = 86400
          + max_ttl                = 31536000
          + min_ttl                = 0
          + target_origin_id       = "S3-simulation-harri-transcoded"
          + trusted_key_groups     = (known after apply)
          + trusted_signers        = (known after apply)
          + viewer_protocol_policy = "allow-all"

          + forwarded_values {
              + headers                 = (known after apply)
              + query_string            = false
              + query_string_cache_keys = []

              + cookies {
                  + forward           = "none"
                  + whitelisted_names = (known after apply)
                }
            }
        }

      + origin {
          + connection_attempts = 3
          + connection_timeout  = 10
          + domain_name         = "beta-harri-transcoded.s3.amazonaws.com"
          + origin_id           = "S3-simulation-harri-transcoded"

          + custom_origin_config {
              + http_port                = 80
              + https_port               = 443
              + origin_keepalive_timeout = 5
              + origin_protocol_policy   = "https-only"
              + origin_read_timeout      = 30
              + origin_ssl_protocols     = [
                  + "TLSv1.2",
                ]
            }

          + s3_origin_config {
              + origin_access_identity = "origin-access-identity/cloudfront/E219MQIHXDF2BU"
            }
        }

      + restrictions {
          + geo_restriction {
              + locations        = (known after apply)
              + restriction_type = "none"
            }
        }

      + viewer_certificate {
          + cloudfront_default_certificate = true
          + minimum_protocol_version       = "TLSv1"
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
````

`resources.tf`
````
module "cloudfront_distributions" {
  source                               = "terraform-aws-modules/cloudfront/aws"
  version                              = "3.4.0"
  for_each                             = var.cloudfront_distributions
  default_cache_behavior               = each.value["default_cache_behavior"] != null ? each.value["default_cache_behavior"] : null
  origin                               = each.value["origin"] != null ? each.value["origin"] : {}
}
````

`variables.tf`
````
##################################################################################
# VARIABLES
##################################################################################

variable "cloudfront_distributions" {
  type = map(object({
    default_cache_behavior = optional(object({
      target_origin_id       = string                                  # The ID of the origin that you want CloudFront to route requests to when they match the path pattern for this cache behavior.
      viewer_protocol_policy = string                                  # The protocol that viewers can use to access the files in the origin specified by target_origin_id when a request matches the path pattern.
      allowed_methods        = optional(list(string), ["GET", "HEAD"]) # List of allowed methods (e.g., GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE).
      cached_methods         = optional(list(string), ["GET", "HEAD"]) # List of cached methods (e.g., GET, HEAD).
      compress               = optional(bool, true)                    # Whether you want CloudFront to automatically compress certain files for this cache behavior.
      lambda_function_association = optional(list(object({
        event_type   = string                # Specifies the event type that triggers a Lambda function invocation.
        lambda_arn   = string                # The ARN of the Lambda function.
        include_body = optional(bool, false) # Whether to include the body content.
      })), [])
      cache_policy_id          = optional(string, null) # The ID of the cache policy for the default cache behavior.
      origin_request_policy_id = optional(string, null) # The ID of the origin request policy for the default cache behavior.
      use_forwarded_values     = optional(bool, true)   # If true, use `forwarded_values` instead of cache and origin request policies.
      query_string             = optional(bool, false)  # Indicates whether you want CloudFront to forward query strings to the origin.
      cookies = optional(object({
        forward           = string                     # Specifies which cookies to forward to the origin.
        whitelisted_names = optional(list(string), []) # Specifies the names of the cookies you want CloudFront to forward to your origin.
        }), {
        forward = "none"
      })
      headers                 = optional(list(string), []) # Specifies the headers you want CloudFront to forward to your origin.
      query_string_cache_keys = optional(list(string), []) # Specifies the list of query string parameters that you want CloudFront to use as a basis for caching.

      min_ttl     = optional(number, 0)        # The minimum amount of time that you want objects to stay in CloudFront caches before CloudFront queries your origin to see if the object has been updated.
      default_ttl = optional(number, 86400)    # The default amount of time that you want objects to stay in CloudFront caches before CloudFront queries your origin to see if the object has been updated.
      max_ttl     = optional(number, 31536000) # The maximum amount of time that you want objects to stay in CloudFront caches before CloudFront queries your origin to see if the object has been updated.
    }), null)
    origin = optional(map(object({
      connection_attempts      = optional(number, 10)
      connection_timeout       = optional(number, 10)
      domain_name              = string
      origin_access_control_id = optional(string, null)
      origin_id                = optional(string, null)
      origin_path              = optional(string, "")
      s3_origin_config = optional(object({
        cloudfront_access_identity_path = optional(string, "")
        origin_access_identity          = optional(string,"")
      }), {})
      custom_origin_config = optional(object({
        http_port                = number
        https_port               = number
        origin_protocol_policy   = string
        origin_ssl_protocols     = list(string)
        origin_keepalive_timeout = optional(number, null)
        origin_read_timeout      = optional(number, null)
      }), { http_port = 80, https_port = 443, origin_protocol_policy   = "https-only", origin_read_timeout = 30, origin_ssl_protocols = [     "TLSv1.2",   ]})
    })), {})
  }))
  default     = {}
  description = "Specify all CloudFront distribution configurations"
}

````

`main.tf`

````
module "distributions" {
  source = "../distributions/"

  cloudfront_distributions = {
    # test resource for s3-origin-config settings
    "test-s3-origin-config" = {
      origin = {
        origin1 = {
          connection_attempts = 3 
          connection_timeout  = 10 
          domain_name         = "beta-harri-transcoded.s3.amazonaws.com" 
          origin_id           = "S3-simulation-harri-transcoded"
          s3_origin_config = {
             cloudfront_access_identity_path = "origin-access-identity/cloudfront/E219MQIHXDF2BU"
           }
        }
      }
      default_cache_behavior = {
        target_origin_id       = "S3-simulation-harri-transcoded"
        viewer_protocol_policy = "allow-all"
        allowed_methods        = ["GET", "HEAD"]
        cached_methods         = ["GET", "HEAD"]
        use_forwarded_values   = true
        compress               = false
      }
    }
    # test resource for custom-origin-config settings
    "test-cf-custom-origin-config" = {
      origin = {
        origin1 = {
          connection_attempts = 3
          connection_timeout  = 10
          domain_name         = "d-i6nfbb6r11.execute-api.us-east-1.amazonaws.com"
          origin_id           = "Custom-d-i6nfbb6r11.execute-api.us-east-1.amazonaws.com"
          custom_origin_config = {
              http_port                = 80
              https_port               = 443
              origin_keepalive_timeout = 5
              origin_protocol_policy   = "https-only"
              origin_read_timeout      = 30
              origin_ssl_protocols     = [
                  "TLSv1.2",
                ]
          }
        }
      }
      default_cache_behavior = {
        target_origin_id       = "S3-simulation-harri-backend"
        viewer_protocol_policy = "redirect-to-https"
        allowed_methods        = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
        cached_methods         = ["GET", "HEAD"]
        cache_policy_id        = "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
        compress               = false
        use_forwarded_values   = false
        headers = [
          "Access-Control-Request-Headers",
          "Access-Control-Request-Method",
          "Origin"
        ]

        default_ttl              = 0
        max_ttl                  = 0
        origin_request_policy_id = "216adef6-5c7f-47e4-b989-5492eafa07d3"
        target_origin_id         = "Custom-d-i6nfbb6r11.execute-api.us-east-1.amazonaws.com"
      }
    }
  }
}

````

**Comment by bryantbiggs** [comment]
oof thats ugly - I would suggest not looping in this manner because you aren't providing any benefit but instead causing self-inflicted issues. just define two module definitions (based on your `cloudfront_distributions`)

**Comment by antonbabenko** [comment]
I agree; this is not what we want to be concerned about in this module. Closing this issue.

**Comment by haytham-salhi** [comment]
Hi @bryantbiggs, we are dealing with many distributions and across many environments. The idea of looping here is we use this in a shared module to achieve the DRY across the distributions within and across environment.

**Comment by bryantbiggs** [comment]
why is that ugly or not "DRY" - I don't prescribe to this notion of "DRY" that comes from traditional software development when it comes to IaC. It doesn't apply. If you follow this approach you are essentially putting all of your eggs in one basket and increasing your blast radius. and in terms of "ugly" - loops will always be harder to read and comprehend so I don't think that is a valid argument here

**Comment by haytham-salhi** [comment]
Frankly, I don't see it is harder to read; it is inside a module after all. And if you want; I can share with you what we need to code when we just need to create a new CloudFront distribution, and how our developer's life gets much easier.

I know we are dealing with declarative language here yet you still have some capabilities in terraform language to apply the same principles of good software development in imperative languages. Passing same default values each time you invoke the module is not a good practice and this applies even in the IaC; it is coding after all. And here's why?
1. You are making your code redundant.
2. Hard to maintain when you need to change a default value for some argument. You need to go through thousands of code in that case, which error prone.
3. In platform engineering, the consumer of that module, e.g., main.tf, does need to know all the arguments that needs to be passed. You need to create some kind of abstraction to make provisioning the resources easily and controllable.

I agree with you only if you are dealing with a small infrastructure/environment. We are not dealing with a small environment, we are dealing with complex and big infrastructure involving multiple environments and regions.

**Comment by bryantbiggs** [comment]
I am afraid we are going to have to agree to disagree. how you wish to structure and use your Terraform is up to you, but unfortunately your practices do not align with ours and therefore the change that is proposed does not make sense in this module.

**Pull request closed without merging**
