### PR TITLE
feat: Added support for Origin Access Controls

### PR DESCRIPTION
**Pull request by pawelpesz**
## Description
Support for **Origin Access Controls**

## Motivation and Context
**Origin Access Controls** superseded **Origin Access Identities** when it comes to securing access to S3 origins. The latter are now presented in AWS UI as legacy.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

The relevant resource was added to the AWS provider in version **4.29.0**.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_origin_access_control

Fixes https://github.com/terraform-aws-modules/terraform-aws-cloudfront/issues/82

## Breaking Changes
None.

## How Has This Been Tested?
- [X] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [X] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [X] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
closing in favor of #97 which is closer to what will be accepted

**Comment by bryantbiggs** [comment]
because it still supports OAIs and just adds OACs - if CloudFront still supports them, then our users will expect the same here

**Comment by pawelpesz** [comment]
I also updated the IAM policy in the example, #97 doesn't do that.

**Comment by pawelpesz** [comment]
@bryantbiggs would take a second look at this? I'd really appreciate it.

**Pull request closed without merging**
